#!/usr/bin/env sh
echo "Rebuilding the Invenio application, this will DESTROY ALL DATA in the database and search engine and load fresh fixtures from the all_data directory"
invenio-cli services destroy
invenio-cli services setup
echo "The 'Failed to setup services.' warning because 'distutils.errors.DistutilsOptionError: no message catalogs found' error does not seem to affect the app"
invenio-cli run &
pipenv run invenio users activate vault@cca.edu # our superadmin user
